### ISSUE TITLE
Declared Logical components not appearing as contained parts of the root logical system

### ISSUE THREAD

**Issue by Ghipag** [DSD-DBS/py-capellambse#231]
Hi all,
I am using the decl.apply() method to update the logical architecture of a (currently empty) Capella model. I am successfully adding the logical components to the Capella model and these appear in the Capella model when I open the project. However these logical components (or coffee machine in my example below) do not have any entries in their "representing parts" or "Typed Elements" properties, nor do they appear in their parents "contained parts" or "sub logical components" properties. 
As a result, the logical components I add to the model in this way can't be added to any Logical Architecture Diagrams [LAB]. Is there a workaround for this?

This is a stripped-down version of the code I am using that should recreate the issue:

```
import capellambse
from capellambse import decl, helpers

capella_model = capellambse.MelodyModel("capella/blank_project/blank_project.aird") # this is a black capella project
    
# to start, get root component and function of logical architecture
root_component = capella_model.la.root_component
structure = capella_model.sa.component_package
root_function = capella_model.sa.root_function

# defining model change in yaml string
model_yaml_update = f"""
- parent: !uuid {root_component.uuid}
  extend:
    components:
      - name: Coffee Machine
        allocated_functions:
          - !promise brew coffee
- parent: !uuid {root_function.uuid}
  extend:
    functions:
      - name: brew coffee
        promise_id: brew coffee
        inputs:
          - name: Portafilter port
          - name: Steam port
            promise_id: steam input
        outputs:
          - name: Fluid port
          - name: Waste port
            promise_id: waste output
      - name: produce steam
        inputs:
          - name: Water port
          - name: Power port
          - name: User command
        outputs:
          - name: Steam port
            promise_id: steam output
      - name: collect process waste
        inputs:
          - name: Waste port
            promise_id: waste input
    exchanges:
      - name: Steam
        source: !promise steam output
        target: !promise steam input
      - name: Waste
        source: !promise waste output
        target: !promise waste input"""

 #apply change to model 
with open(output_file_name, "w") as f:
    f.write(model_yaml_update)
 
decl.apply(capella_model,output_file_name)
capella_model.save()
```

Thanks for any help
