### ISSUE TITLE
Declarative modeling: add find by name functionality

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#232]
While using declarative modeling I realized referencing objects by uuid is not very human-friendly. In our non-declarative applications (i.e. doc templates) we frequently refer to things by name. I think same thing here would be very helpful:
```
parent: !find-by-name brew coffee in SA functions
``` 
or something like that.

Maybe we could use some extra keywords for scope reduction (so that it knows that we are searching for an LA component or SA function.

**Comment by Wuestengecko** [comment]
What do you think about this proposal?

```yaml
- parent: !find
    type: SystemFunction
    name: brew coffee
  create: ...
```

Except for `type` (which is special cased to look at the class), this approach would be extensible to allow filtering for every attribute that a model object could have. For example, if you were searching for a Requirement and you know that its combination of `chapter_name` and `foreign_id` makes it unique, you could use:

```yaml
- parent: !find
    type: Requirement
    chapter_name: Chapter 3
    foreign_id: 7
  create: ...
```
